services:
  - type: web
    name: eproject-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: eproject-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    
databases:
  - name: eproject-db
    databaseName: eproject
    plan: free
